/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/partner/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company catalog (paginated, filterable) */
        get: operations["partnerListCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company detail with embedded 12-month pricing + activity history */
        get: operations["partnerGetCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/companies/{slug}/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pricing history (24 months) + funding rounds */
        get: operations["partnerGetCompanyCharts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/companies/{slug}/funding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All funding rounds for a company */
        get: operations["partnerGetCompanyFunding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/companies/{slug}/daily-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily prices (institutional + retail) for a company
         * @description One point per pricing day, ascending. Filter with `from`/`to` (inclusive, UTC days); `limit` keeps the most recent N days of the range. A company with no daily prices returns an empty series.
         */
        get: operations["partnerGetCompanyDailyPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/daily-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily prices for every priced company on one day
         * @description Bulk snapshot: every company that has a price on `date` (default: the latest day with prices). Use this for a daily pull instead of one call per company.
         */
        get: operations["partnerListDailyPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LBX indexes with current metrics */
        get: operations["partnerListIndexes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/indexes/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index level history */
        get: operations["partnerGetIndexHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active, publicly visible opportunities */
        get: operations["partnerListOpportunities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/opportunities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunity detail */
        get: operations["partnerGetOpportunity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All orders on the partner account, newest first */
        get: operations["partnerListOrders"];
        put?: never;
        /**
         * Place an order (returns a one-shot signing URL)
         * @description Places an order for the partner’s investor account against a tokenized opportunity and mints the prospectus signing envelope. Send an `Idempotency-Key` header (any string unique per order attempt) to make retries safe: a repeat with the same key returns the original order instead of creating a second one.
         */
        post: operations["partnerCreateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order status + economics (poll this) */
        get: operations["partnerGetOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/confirm-signing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the prospectus is signed; advances to awaiting_payment
         * @description Call after the signatory completes the DocuSign envelope. Idempotent. Returns 400 "Documents not signed yet" if called too early — retry after signing.
         */
        post: operations["partnerConfirmOrderSigning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/resume-signing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-issue the signing URL for an order still awaiting signature */
        post: operations["partnerResumeOrderSigning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an unpaid order */
        post: operations["partnerCancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/opportunity-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The offer’s legal documents (references) for an order */
        get: operations["partnerListOrderOpportunityDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/opportunity-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Short-lived download URL for one legal document */
        get: operations["partnerGetOrderOpportunityDocumentUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/orders/{id}/documents/{docUid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a settlement document (signed prospectus, receipt)
         * @description Document ids come from the order’s `settlementDocuments` array, populated once the custody platform issues them.
         */
        get: operations["partnerDownloadOrderDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings (per position + grouped per offer) with live valuation and a summary */
        get: operations["partnerGetPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio value over time */
        get: operations["partnerGetPortfolioHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/positions/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One position’s value over time */
        get: operations["partnerGetPositionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityHistoryPoint: {
            quarter: string;
            activityScore: number | null;
        };
        ChartFundingPoint: {
            date: string;
            round: string;
            size: number | null;
            valuation: number | null;
            pps: number | null;
        };
        ChartPricingPoint: {
            date: string;
            price: number | null;
            valuation: number | null;
            premium: number | null;
        };
        CompanyChartsResponse: {
            pricingHistory: components["schemas"]["ChartPricingPoint"][];
            fundingRounds: components["schemas"]["ChartFundingPoint"][];
        };
        /** @enum {string|null} */
        CompanyCohort: "liquid" | "semi-liquid" | null;
        CompanyDailyPricesResponse: {
            company: string;
            slug: string;
            /** @description Ascending by date */
            points: components["schemas"]["DailyPricePoint"][];
        };
        CompanyDetail: {
            slug: string;
            name: string;
            industry: string;
            industrySlug?: string;
            vertical: string;
            cohort: components["schemas"]["CompanyCohort"];
            inLBX25: boolean;
            launchbayPrice: number;
            impliedValuation: number | null;
            secondaryPremium: number | null;
            lastBidShare: number | null;
            lastAskShare: number | null;
            lastAverageSecondarySpread: number | null;
            activityScore: number | null;
            activityRanking: number | null;
            activityRankingChange: components["schemas"]["RankingChange"];
            threeMonthReturn: number | null;
            oneYearReturn: number | null;
            ipoStatus: string | null;
            yearOfIPO: number | null;
            lastRound: string | null;
            lastRoundDate: string | null;
            domainName: string | null;
            pricingHistory: components["schemas"]["PricingHistoryPoint"][];
            activityHistory: components["schemas"]["ActivityHistoryPoint"][];
            leo?: components["schemas"]["LeoStarterPack"];
        };
        CompanyDetailResponse: {
            company: components["schemas"]["CompanyDetail"];
        };
        CompanyFundingResponse: {
            company: string;
            rounds: components["schemas"]["FundingRound"][];
        };
        CompanyListItem: {
            slug: string;
            platformId: number | null;
            name: string;
            industry: string;
            industrySlug?: string;
            vertical: string;
            cohort: components["schemas"]["CompanyCohort"];
            inLBX25: boolean;
            launchbayPrice: number;
            impliedValuation: number | null;
            secondaryPremium: number | null;
            activityScore: number | null;
            activityRanking: number | null;
            activityRankingChange: components["schemas"]["RankingChange"];
            threeMonthReturn: number | null;
            oneYearReturn: number | null;
            hideFromReturnRanking: boolean;
            lastRound: string | null;
            lastRoundDate: string | null;
            lastPrimaryValuation: number | null;
        };
        CompanyListResponse: {
            items: components["schemas"]["CompanyListItem"][];
            total: number;
        };
        DailyPriceListItem: {
            slug: string;
            company: string;
            institutionalPrice: number | null;
            retailPrice: number | null;
        };
        DailyPricePoint: {
            /**
             * @description Pricing day (UTC, YYYY-MM-DD)
             * @example 2026-09-08
             */
            date: string;
            institutionalPrice: number | null;
            retailPrice: number | null;
        };
        DailyPricesListResponse: {
            /** @description The pricing day served; null when no prices exist yet */
            date: string | null;
            /** @description Sorted by company name */
            items: components["schemas"]["DailyPriceListItem"][];
        };
        ErrorResponse: {
            /** @example Resource not found */
            error: string;
            /** @example NOT_FOUND */
            code?: string;
            details?: unknown;
        };
        FundingRound: {
            date: string | null;
            round: string | null;
            roundSize: number | null;
            valuation: number | null;
            pricePerShare: number | null;
        };
        IndexHistoryPoint: {
            date: string;
            value: number | null;
        };
        IndexHistoryResponse: {
            indexName: string;
            history: components["schemas"]["IndexHistoryPoint"][];
        };
        IndexItem: {
            id: string;
            indexName: string;
            indexType: string;
            currentValue: number | null;
            previousLevel: number | null;
            initialValue: number | null;
            initialDate: string | null;
            portfolioDate: string | null;
            marketCap: number | null;
            totalHoldings: number | null;
            oneMonthPerformance: number | null;
            threeMonthPerformance: number | null;
            oneYearPerformance: number | null;
            fiftyTwoWeeksLow: number | null;
            fiftyTwoWeeksHigh: number | null;
            activityShare: number | null;
        };
        IndexListResponse: {
            items: components["schemas"]["IndexItem"][];
        };
        LeoStarterPack: {
            starters: components["schemas"]["LeoSuggestion"][];
            version: number;
            updatedAt: string;
            strategy: components["schemas"]["LeoStarterStrategy"];
        };
        /** @enum {string} */
        LeoStarterStrategy: "manual" | "template";
        LeoSuggestion: {
            label: string;
            prompt: string;
        };
        OfferBody: {
            lede: string | null;
            vehicle: string | null;
            thesis: string[];
            facts: [
                string,
                string
            ][];
        } | null;
        OfferEconomics: {
            subscriptionPrice: number | null;
            minInvestment: number | null;
            maxInvestment: number | null;
            tokenIssueFeePct: number | null;
            adminFeePct: number | null;
            adminFeeYears: number | null;
            subscriptionCommencementDate: string | null;
            subscriptionDeadline: string | null;
            investorDeadline: string | null;
            forQualifiedOnly: boolean;
            allocation: {
                total: number | null;
                remaining: number | null;
                soldPct: number | null;
            };
            /** @enum {string} */
            displayStatus: "coming_soon" | "active" | "fully_subscribed" | "closed";
        } | null;
        OpportunityActivityPoint: {
            quarter: string;
            activityScore: number | null;
        };
        OpportunityCompanyMetrics: {
            industry: string | null;
            domainName: string | null;
            smallLogo: string | null;
            /** @enum {string|null} */
            cohort: "liquid" | "semi-liquid" | null;
            launchbayIndexStatus: boolean;
            launchbayPricePerShare: number | null;
            impliedValuation: number | null;
            secondaryPremium: number | null;
            impliedValuationMonthlyChange: number | null;
            lastPrimaryValuation: number | null;
            lastPrimaryPPS: number | null;
            lastRound: string | null;
            lastRoundDate: string | null;
            activityScore: number | null;
            activityRanking: number | null;
            threeMonthReturn: number | null;
            oneYearReturn: number | null;
            ipoStatus: string | null;
            estimatedIPOValuation: number | null;
        } | null;
        OpportunityFundingRound: {
            roundDate: string | null;
            fundingRound: string | null;
            roundSize: number | null;
            roundValuation: number | null;
            roundPricePerShare: number | null;
        };
        OpportunityHolding: {
            platformId: number | null;
            name: string | null;
            slug: string | null;
            subscriptionPrice: number | null;
            sharePercent: number | null;
            impliedValuation: number | null;
            domainName: string | null;
            smallLogo: string | null;
            deepDiveUrl: string | null;
            sharesPerToken: number | null;
        };
        OpportunityLegalDocument: {
            key: string;
            title: string;
            size: number | null;
        };
        /** @default null */
        OpportunityPortfolio: {
            structure: string;
            thesis: string | null;
            holdingsCount: number;
            holdings: components["schemas"]["OpportunityHolding"][];
        } | null;
        OpportunityPricingPoint: {
            pricingDate: string;
            launchbayPricePerShare: number | null;
            secondaryPremium: number | null;
            impliedValuation: number | null;
        };
        OrderCancelRequest: {
            note?: string;
        };
        OrderCreateRequest: {
            opportunitySlug: string;
            amount: number;
        };
        /** @enum {string} */
        OrderStatus: "created" | "awaiting_signature" | "documents_signed" | "awaiting_payment" | "payment_details_sent" | "payment_received" | "accepted" | "completed" | "cancelled" | "rejected" | "expired" | "failed" | "lost";
        PartnerHolding: {
            opportunitySlug: string;
            opportunityName: string;
            domainName: string | null;
            numberOfUnits: number;
            investedTotal: number;
            positionValue: number | null;
            pnlVsSubscriptionPct: number | null;
            custodyAssetId: string | null;
            lots: components["schemas"]["PartnerPosition"][];
        };
        PartnerOpportunity: {
            slug: string;
            /** @enum {string} */
            type: "company" | "portfolio";
            /**
             * @default non-tokenized
             * @enum {string}
             */
            listingType: "tokenized" | "non-tokenized";
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "tester-only" | "staging-only";
            displayName: string;
            tagline: string;
            displayOrder: number;
            /** @default false */
            featured: boolean;
            heroImage: string | null;
            logoOverride: string | null;
            minInvestment: number;
            ctaLabel: string;
            ctaUrl: string;
            platformId: number | null;
            metrics: components["schemas"]["OpportunityCompanyMetrics"];
            portfolio?: components["schemas"]["OpportunityPortfolio"];
            economics: components["schemas"]["OfferEconomics"];
            body: components["schemas"]["OfferBody"];
            /** @default null */
            legalDocuments: components["schemas"]["OpportunityLegalDocument"][] | null;
            custodyAssetId: string | null;
        };
        PartnerOpportunityDetail: {
            slug: string;
            /** @enum {string} */
            type: "company" | "portfolio";
            /**
             * @default non-tokenized
             * @enum {string}
             */
            listingType: "tokenized" | "non-tokenized";
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "tester-only" | "staging-only";
            displayName: string;
            tagline: string;
            displayOrder: number;
            /** @default false */
            featured: boolean;
            heroImage: string | null;
            logoOverride: string | null;
            minInvestment: number;
            ctaLabel: string;
            ctaUrl: string;
            platformId: number | null;
            metrics: components["schemas"]["OpportunityCompanyMetrics"];
            portfolio?: components["schemas"]["OpportunityPortfolio"];
            economics: components["schemas"]["OfferEconomics"];
            body: components["schemas"]["OfferBody"];
            /** @default null */
            legalDocuments: components["schemas"]["OpportunityLegalDocument"][] | null;
            fundingRounds: components["schemas"]["OpportunityFundingRound"][];
            pricingHistory: components["schemas"]["OpportunityPricingPoint"][];
            activityHistory: components["schemas"]["OpportunityActivityPoint"][];
            metricsUpdatedAt: string | null;
            custodyAssetId: string | null;
        };
        PartnerOpportunityDetailResponse: {
            opportunity: components["schemas"]["PartnerOpportunityDetail"];
        };
        PartnerOpportunityListResponse: {
            items: components["schemas"]["PartnerOpportunity"][];
        };
        PartnerOpportunitySnapshot: {
            slug: string;
            name: string;
            minInvestment: number;
            pricePerUnit: number | null;
            subscriptionPrice: number | null;
            tokenIssueFeePct: number | null;
            adminFeePct: number | null;
            adminFeeYears: number | null;
            custodyAssetId: string | null;
        };
        PartnerOrder: {
            id: string;
            opportunitySlug: string;
            opportunityName: string;
            status: components["schemas"]["OrderStatus"];
            initialAmount: number;
            numberOfUnits: number | null;
            placementPrice: number | null;
            subscriptionPrice: number | null;
            positionValueAtAccepted: number | null;
            tokenIssueFee: number | null;
            tokenIssueFeeAmount: number | null;
            adminFee: number | null;
            adminFeeYears: number | null;
            adminFeeAmount: number | null;
            adminFeePaidUntil: string | null;
            totalAmount: number | null;
            paymentConfirmedDate: string | null;
            signingUrl: string | null;
            failureReason: string | null;
            createdAt: string;
            updatedAt: string;
            opportunitySnapshot: components["schemas"]["PartnerOpportunitySnapshot"];
            settlementDocuments: components["schemas"]["SettlementDocument"][];
            custodyOrderId: string | null;
            statusHistory: components["schemas"]["PartnerOrderStatusEvent"][];
        };
        PartnerOrderCreateRequest: components["schemas"]["OrderCreateRequest"] & {
            /**
             * Format: uri
             * @description Where DocuSign sends the signer after signing. Defaults to the LBX web app; partners should pass their own page.
             */
            returnUrl?: string;
        };
        PartnerOrderListResponse: {
            items: components["schemas"]["PartnerOrder"][];
        };
        PartnerOrderOpportunityDocuments: {
            opportunitySlug: string;
            opportunityName: string;
            documents: {
                key: string;
                title: string;
                size: number | null;
            }[];
        };
        PartnerOrderResponse: {
            order: components["schemas"]["PartnerOrder"];
        };
        PartnerOrderStatusEvent: {
            status: components["schemas"]["OrderStatus"];
            at: string;
            /** @enum {string} */
            by: "investor" | "docusign" | "manager" | "custody" | "system";
            note: string | null;
        };
        PartnerPortfolio: {
            summary: {
                investedTotal: number;
                valueTotal: number;
                gain: number;
                gainPct: number;
                activePositions: number;
            };
            positions: components["schemas"]["PartnerPosition"][];
            holdings: components["schemas"]["PartnerHolding"][];
        };
        PartnerPosition: {
            id: string;
            orderId: string;
            opportunitySlug: string;
            opportunityName: string;
            numberOfUnits: number;
            initialAmount: number;
            subscriptionPrice: number | null;
            lbxPriceBeforeAccepted: number | null;
            positionValueAtAccepted: number | null;
            pricingDate: string | null;
            launchbayPricePerShare: number | null;
            impliedValuation: number | null;
            indicativeValue: number | null;
            positionValue: number | null;
            pnlVsSubscriptionPct: number | null;
            tokenIssueFeeAmount: number | null;
            adminFeeAmount: number | null;
            totalAmount: number | null;
            currentValue: number | null;
            adminFeePaidUntil: string | null;
            constituents: components["schemas"]["PositionConstituent"][];
            createdAt: string;
            custodyAssetId: string | null;
        };
        PartnerSigningRequest: {
            /** Format: uri */
            returnUrl?: string;
        };
        PortfolioHistoryPoint: {
            date: string;
            portfolioValue: number;
        };
        PortfolioHistoryResponse: {
            points: components["schemas"]["PortfolioHistoryPoint"][];
        };
        PositionConstituent: {
            companyCode: string;
            slug: string | null;
            name: string;
            industry: string;
            sharesPerToken: number;
            priceAtCreated: number | null;
        };
        PositionHistoryPoint: {
            date: string;
            positionValue: number;
            pnlVsSubscriptionPct: number | null;
            launchbayPricePerShare: number | null;
            impliedValuation: number | null;
        };
        PositionHistoryResponse: {
            points: components["schemas"]["PositionHistoryPoint"][];
        };
        PresignedUrl: {
            url: string;
            expiresIn: number;
        };
        PricingHistoryPoint: {
            date: string;
            pricePerShare: number | null;
            impliedValuation: number | null;
        };
        /** @enum {string|null} */
        RankingChange: "up" | "down" | "same" | "new" | null;
        SettlementDocument: {
            uid: string;
            fileName: string;
            size: number | null;
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    partnerListCompanies: {
        parameters: {
            query?: {
                search?: string;
                /** @description One or more industry names. Repeat the param for multiple. */
                industry?: string | string[];
                cohort?: "liquid" | "semi-liquid";
                /** @description true = LBX25 constituents only; false = exclude constituents */
                inLBX25?: "true" | "false";
                minSecondaryPremium?: number | null;
                maxSecondaryPremium?: number | null;
                /** @description Min lastPrimaryValuation in USD */
                minValuation?: number | null;
                maxValuation?: number | null;
                minActivityScore?: number | null;
                maxActivityScore?: number | null;
                /** @description Min lastRoundDate (ISO 8601) */
                dateFrom?: string;
                dateTo?: string;
                /** @description Sort field. Default: lastRoundDate. */
                sortBy?: "activityScore" | "activityRanking" | "launchbayPricePerShare" | "impliedValuation" | "secondaryPremium" | "lastRoundDate" | "threeMonthReturn" | "oneYearReturn" | "lastAverageSecondarySpread" | "companyName";
                /** @description Sort direction. Default: desc. */
                sortOrder?: "asc" | "desc";
                limit?: number;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListResponse"];
                };
            };
            /** @description Bad query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetCompanyCharts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyChartsResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetCompanyFunding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Funding rounds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyFundingResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetCompanyDailyPrices: {
        parameters: {
            query?: {
                /** @description Inclusive start day (UTC, YYYY-MM-DD) */
                from?: string;
                /** @description Inclusive end day (UTC, YYYY-MM-DD) */
                to?: string;
                /** @description Most recent N days within the range (1-2000). Default 365. */
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily price series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDailyPricesResponse"];
                };
            };
            /** @description Bad query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerListDailyPrices: {
        parameters: {
            query?: {
                /** @description Pricing day (UTC, YYYY-MM-DD). Default: the latest day that has prices. */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prices for the day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPricesListResponse"];
                };
            };
            /** @description Bad query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerListIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexListResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetIndexHistory: {
        parameters: {
            query?: {
                /** @description Months of history (1-120). Default 12. */
                months?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexHistoryResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerListOpportunities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opportunities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOpportunityListResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetOpportunity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opportunity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOpportunityDetailResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerListOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderListResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerCreateOrder: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PartnerOrderCreateRequest"];
            };
        };
        responses: {
            /** @description Order created (or the existing order for a repeated Idempotency-Key) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderResponse"];
                };
            };
            /** @description Validation error (offer closed, minimum, fees unset, …) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Partner account not eligible (suspended, not accredited, not registered) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerConfirmOrderSigning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order (documents_signed → awaiting_payment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderResponse"];
                };
            };
            /** @description Not signed yet / wrong status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerResumeOrderSigning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PartnerSigningRequest"];
            };
        };
        responses: {
            /** @description Order with a fresh signingUrl */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderResponse"];
                };
            };
            /** @description Order not awaiting signature */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerCancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OrderCancelRequest"];
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderResponse"];
                };
            };
            /** @description Not cancellable from its current status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerListOrderOpportunityDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOrderOpportunityDocuments"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetOrderOpportunityDocumentUrl: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrl"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Partner account not identity-verified */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerDownloadOrderDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                docUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file (streamed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Order has no custody-side documents yet */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPortfolio"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetPortfolioHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Value series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    partnerGetPositionHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Value series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionHistoryResponse"];
                };
            };
            /** @description Missing or invalid partner key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
